services:
  # Backend API service
  - type: web
    name: visitor-management-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    healthCheckPath: /api/flats
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_USERNAME
        value: panchadmin
      - key: ADMIN_PASSWORD
        value: admin@1234
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
